[package]
name = "riscv_vplic"
version = "0.2.1"
edition = "2021"
authors = ["Jingyu liu <liujingyu24s@ict.ac.cn>"]
description = "RISCV Virtual PLIC implementation."
documentation = "https://arceos-hypervisor.github.io/riscv_vplic"
repository = "https://github.com/arceos-hypervisor/riscv_vplic"
readme = "README.md"
categories = ["os", "no-std"]
keywords = ["hypervisor", "kernel", "vplic"]
license = "Apache-2.0"

[features]
default = []

[dependencies]
axaddrspace = "0.1.4"
axdevice_base = "0.2.1"
axvisor_api = "0.1"

axerrno = "0.1.0"
bitmaps = { version = "3.2", default-features = false }
log = "0.4"
spin = "0.9"

riscv-h = "0.1"

[package.metadata.docs.rs]
default-target = ["riscv64gc-unknown-none-elf"]
targets = ["riscv64gc-unknown-none-elf"]