[package]
name = "riscv_vplic"
authors = ["Jingyu liu <liujingyu24s@ict.ac.cn>"]
version = "0.1.0"
edition = "2021"
categories = ["os", "no-std"]
description = "RISCV Virtual PLIC implementation."
repository = "https://github.com/arceos-hypervisor/riscv_vplic"
keywords = ["hypervisor", "kernel", "vplic"]
license = "Apache-2.0"

[features]
default = []

[dependencies]
axaddrspace = "0.1.4"
axdevice_base = "0.2.1"
axvisor_api = "0.1"

axerrno = "0.1.0"
bitmaps = { version = "3.2", default-features = false }
log = "0.4"
spin = "0.9"

riscv-h = "0.1"
